"""Workflow for segmenting a CT image and converting anatomy groups to VTK surfaces and meshes.

The workflow segments a 3D CT image using a chosen backend, then extracts one VTP
(surface) and one VTU (tetrahedral volume mesh, generated by netgen from that
surface) per non-empty anatomy group.  Each output object carries anatomy
metadata and solid color from :class:`USDAnatomyTools` as field and cell data
so that downstream tools (PyVista, Paraview, USD pipeline) can use them
directly.

Typical usage::

    import itk
    from physiomotion4d import (
        SegmentChestTotalSegmentatorWithContrast,
        WorkflowConvertImageToVTK,
    )

    ct = itk.imread('chest_ct.nii.gz')
    segmenter = SegmentChestTotalSegmentatorWithContrast()
    workflow = WorkflowConvertImageToVTK(segmentation_method=segmenter)
    result = workflow.run_workflow(
        ct, surface_target_reduction=0.5, mesh_target_reduction=0.7
    )

    # Combined single-file output (default)
    WorkflowConvertImageToVTK.save_combined_surface(result['surfaces'], './out', prefix='patient')
    WorkflowConvertImageToVTK.save_combined_mesh(result['meshes'], './out', prefix='patient')

    # Per-group split output
    WorkflowConvertImageToVTK.save_surfaces(result['surfaces'], './out', prefix='patient')
    WorkflowConvertImageToVTK.save_meshes(result['meshes'], './out', prefix='patient')
"""

import logging
import os
from typing import Any, Optional, cast

import itk
import numpy as np
import pyvista as pv

from .contour_tools import ContourTools
from .physiomotion4d_base import PhysioMotion4DBase
from .segment_anatomy_base import SegmentAnatomyBase
from .segment_chest_total_segmentator_with_contrast import (
    SegmentChestTotalSegmentatorWithContrast,
)
from .usd_anatomy_tools import USDAnatomyTools


class WorkflowConvertImageToVTK(PhysioMotion4DBase):
    """Segment a CT image and produce per-anatomy-group VTK surfaces and meshes.

    ``segmentation_method`` accepts a pre-configured
    :class:`SegmentAnatomyBase` instance (e.g. :class:`SegmentChestTotalSegmentator`,
    :class:`SegmentChestTotalSegmentatorWithContrast` for contrast-enhanced
    studies, :class:`SegmentHeartSimpleware`, or
    :class:`SegmentHeartSimplewareTrimmedBranches` for cardiac-only
    segmentation with pulmonary/great-vessel branches trimmed). Defaults to
    a new :class:`SegmentChestTotalSegmentator` when omitted.

    **Output anatomy groups**

    Determined by the active segmenter's :attr:`SegmentAnatomyBase.taxonomy`
    (see :attr:`ANATOMY_GROUPS`).  Groups that are empty after segmentation
    are silently skipped.

    **VTK object annotation**

    Each :class:`pyvista.PolyData` surface and :class:`pyvista.UnstructuredGrid` mesh
    returned by :meth:`run_workflow` carries:

    - ``field_data['AnatomyGroup']`` — anatomy group name, e.g. ``'heart'``.
    - ``field_data['SegmentationLabelNames']`` — individual structure names within the
      group (e.g. ``['left_ventricle', 'right_ventricle', …]``).
    - ``field_data['SegmentationLabelIds']`` — corresponding integer label IDs.
    - ``field_data['AnatomyColor']`` — RGB float color from :class:`USDAnatomyTools`.
    - ``cell_data['Color']`` — RGBA uint8 array (n_cells × 4) for direct VTK rendering.

    **I/O contract**

    :meth:`run_workflow` performs *no* file I/O.  Use the static helpers
    :meth:`save_surfaces`, :meth:`save_meshes`, :meth:`save_combined_surface`, and
    :meth:`save_combined_mesh` — or the CLI ``physiomotion4d-convert-image-to-vtk`` — to
    write results to disk.
    """

    def __init__(
        self,
        segmentation_method: Optional[SegmentAnatomyBase] = None,
        log_level: int | str = logging.INFO,
    ) -> None:
        """Initialize the workflow.

        Args:
            segmentation_method: Segmentation backend instance. Defaults to
                a new :class:`SegmentChestTotalSegmentatorWithContrast` when None.
            log_level: Logging level.  Default: ``logging.INFO``.

        Raises:
            TypeError: If segmentation_method is neither None nor a
                SegmentAnatomyBase instance.
        """
        super().__init__(class_name=self.__class__.__name__, log_level=log_level)

        if segmentation_method is None:
            segmentation_method = SegmentChestTotalSegmentatorWithContrast(
                log_level=log_level
            )
        elif not isinstance(segmentation_method, SegmentAnatomyBase):
            raise TypeError(
                "segmentation_method must be a SegmentAnatomyBase instance or None"
            )
        self._segmenter: SegmentAnatomyBase = segmentation_method
        self._contour_tools: ContourTools = ContourTools(log_level=log_level)

        #: Anatomy group names registered by the active segmenter's taxonomy,
        #: in the order they were first added.
        self.ANATOMY_GROUPS: tuple[str, ...] = tuple(
            self._segmenter.taxonomy.group_names()
        )

        # Build anatomy-group → RGB color from USDAnatomyTools.
        # USDAnatomyTools sets up its color dicts entirely in __init__ without
        # accessing the stage, so stage=None is safe for this lookup-only use.
        _anatomy_tools = USDAnatomyTools(stage=None, log_level=log_level)
        supported_types = set(_anatomy_tools.get_anatomy_types())
        self._anatomy_color_map: dict[str, tuple[float, float, float]] = {
            group: _anatomy_tools.get_anatomy_diffuse_color(group)
            for group in self.ANATOMY_GROUPS
            if group in supported_types
        }

    # ─────────────────────────── Internal helpers ──────────────────────────

    def _get_label_info_for_group(self, group: str) -> tuple[list[str], list[int]]:
        """Return ``(label_names, label_ids)`` for *group* from the active segmenter.

        Reads the segmenter's :class:`AnatomyTaxonomy`. Returns empty lists if
        the group is not present (e.g. HeartSimpleware does not register
        lung/bone).
        """
        mask_ids = self._segmenter.taxonomy.labels_in_group(group)
        return list(mask_ids.values()), list(mask_ids.keys())

    @staticmethod
    def _annotate(
        vtk_obj: pv.DataSet,
        group: str,
        label_names: list[str],
        label_ids: list[int],
        color_rgb: tuple[float, float, float],
    ) -> None:
        """Attach anatomy metadata and solid RGBA color to a VTK object **in-place**.

        Sets:

        - ``field_data['AnatomyGroup']`` — group name.
        - ``field_data['SegmentationLabelNames']`` — individual label names.
        - ``field_data['SegmentationLabelIds']`` — integer label IDs (int32).
        - ``field_data['AnatomyColor']`` — RGB float32 color.
        - ``cell_data['Color']`` — RGBA uint8 solid color (n_cells × 4).
        """
        vtk_obj.field_data["AnatomyGroup"] = np.array([group])
        vtk_obj.field_data["SegmentationLabelNames"] = np.array(
            label_names if label_names else [group]
        )
        vtk_obj.field_data["SegmentationLabelIds"] = np.array(label_ids, dtype=np.int32)
        vtk_obj.field_data["AnatomyColor"] = np.array(color_rgb, dtype=np.float32)

        r, g, b = color_rgb
        rgba = np.array([int(r * 255), int(g * 255), int(b * 255), 255], dtype=np.uint8)
        if vtk_obj.n_cells > 0:
            vtk_obj.cell_data["Color"] = np.tile(rgba, (vtk_obj.n_cells, 1))

    def _extract_surface(self, mask_image: Any) -> Optional[pv.PolyData]:
        """Extract a smoothed triangulated surface (VTP) from a binary mask image.

        Delegates to :meth:`ContourTools.extract_contours`.

        Returns:
            Smoothed :class:`pyvista.PolyData`, or ``None`` if the mask is empty.
        """
        arr = itk.GetArrayFromImage(mask_image)
        if int(arr.sum()) == 0:
            return None
        return self._contour_tools.extract_contours(mask_image)

    def _extract_mesh(
        self, surface: pv.PolyData, mesh_target_reduction: float = 0.0
    ) -> Optional[pv.UnstructuredGrid]:
        """Generate a tetrahedral volume mesh (VTU) from a closed surface via netgen.

        Optionally decimates the surface with
        :meth:`pyvista.PolyDataFilters.decimate_pro` before meshing — netgen
        has no post-hoc decimation of its own, so a coarser input surface is
        the only way to get a coarser tetrahedral mesh out.

        Builds netgen's surface mesh directly from *surface*'s indexed
        points/triangles rather than round-tripping through an STL file.
        STL has no shared-vertex topology, so every triangle corner is
        written independently; float32 rounding during that round-trip can
        make two corners that were exactly the same point diverge by ~1e-6,
        which is well within netgen's own "identical point" merge tolerance
        and makes its STL reader spin forever trying to reconcile them
        (observed hang on the Taubin-smoothed surfaces this method actually
        receives). Adding points/triangles directly preserves the exact
        shared-vertex indices already present in *surface*, so there is
        nothing for netgen to reconcile.

        Args:
            surface: Closed, triangulated surface for one anatomy group (as
                returned by :meth:`_extract_surface`).
            mesh_target_reduction: Fraction in ``[0, 1)`` of surface triangles
                to remove via ``decimate_pro(mesh_target_reduction,
                preserve_topology=True)`` before meshing.  ``0.0`` (default)
                skips decimation and meshes the surface as given.

        Returns:
            :class:`pyvista.UnstructuredGrid` of tetrahedral cells, or
            ``None`` if the surface is empty or netgen produced no volume
            mesh from it.
        """
        if surface.n_points == 0:
            return None

        meshing_surface = surface.triangulate().clean()
        if mesh_target_reduction > 0.0:
            meshing_surface = meshing_surface.decimate_pro(
                mesh_target_reduction, preserve_topology=True
            )

        import netgen.meshing as ngm  # noqa: PLC0415

        triangles = meshing_surface.faces.reshape(-1, 4)[:, 1:4]
        ngmesh = ngm.Mesh()
        ngmesh.dim = 3
        point_ids = [
            ngmesh.Add(ngm.MeshPoint(ngm.Pnt(*point)))
            for point in meshing_surface.points
        ]
        face_descriptor = ngmesh.Add(ngm.FaceDescriptor(surfnr=1, domin=1, domout=0))
        for triangle in triangles:
            ngmesh.Add(ngm.Element2D(face_descriptor, [point_ids[i] for i in triangle]))
        ngmesh.GenerateVolumeMesh()

        elements = ngmesh.Elements3D()
        if len(elements) == 0:
            self.log_warning("netgen produced no volume mesh for this surface")
            return None

        points = ngmesh.Coordinates()
        tets = np.array(
            [[vertex.nr - 1 for vertex in element.vertices] for element in elements],
            dtype=np.int64,
        )
        # netgen's tet vertex order is opposite VTK_TETRA's right-hand
        # convention (confirmed by negative cell volumes); swapping the last
        # two indices restores positive-volume orientation.
        tets = tets[:, [0, 1, 3, 2]]
        cells = np.hstack(
            [np.full((tets.shape[0], 1), 4, dtype=np.int64), tets]
        ).flatten()
        cell_types = np.full(tets.shape[0], pv.CellType.TETRA, dtype=np.uint8)
        return pv.UnstructuredGrid(cells, cell_types, points)

    # ─────────────────────────── Main workflow ─────────────────────────────

    def run_workflow(
        self,
        input_image: Any,
        anatomy_groups: Optional[list[str]] = None,
        surface_target_reduction: float = 0.0,
        mesh_target_reduction: float = 0.0,
    ) -> dict[str, Any]:
        """Segment the CT image and extract per-anatomy-group VTK objects.

        Args:
            input_image: Input 3D CT image (``itk.Image``).
            anatomy_groups: Subset of anatomy groups to process.  ``None`` (default)
                processes all non-empty groups.  Valid names are given by
                :attr:`ANATOMY_GROUPS`, derived from the active segmenter's
                taxonomy.
            surface_target_reduction: Fraction in ``[0, 1)`` of surface
                triangles to remove via ``decimate_pro(surface_target_reduction,
                preserve_topology=True)``.  ``0.0`` (default) skips decimation.
            mesh_target_reduction: Fraction in ``[0, 1)`` of the surface's
                triangles to remove (via the same ``decimate_pro`` call)
                before it is handed to netgen for tetrahedral meshing.  A
                coarser input surface yields a coarser volume mesh — netgen
                itself has no post-hoc decimation.  ``0.0`` (default) skips
                decimation and meshes the surface as extracted.

        Returns:
            ``dict`` with the following keys:

            - ``'surfaces'`` — ``dict[str, pv.PolyData]``: smoothed surface per group.
            - ``'meshes'`` — ``dict[str, pv.UnstructuredGrid]``: tetrahedral volume
              mesh per group, generated by netgen from that group's surface.
            - ``'labelmap'`` — ``itk.Image``: detailed per-structure segmentation
              labelmap from the segmenter.
            - ``'segmentation_masks'`` — ``dict[str, itk.Image]``: per-group binary
              masks used to produce the VTK objects.

        Raises:
            ValueError: If any name in *anatomy_groups* is invalid.
        """
        self.log_section("STARTING IMAGE TO VTK WORKFLOW")

        # Validate requested groups
        if anatomy_groups is not None:
            invalid = [g for g in anatomy_groups if g not in self.ANATOMY_GROUPS]
            if invalid:
                raise ValueError(
                    f"Unknown anatomy groups: {invalid}. "
                    f"Valid: {list(self.ANATOMY_GROUPS)}"
                )
            groups_to_process: list[str] = list(anatomy_groups)
        else:
            groups_to_process = list(self.ANATOMY_GROUPS)

        # Run segmenter
        self.log_info("Running segmenter: %s", type(self._segmenter).__name__)

        self.log_section("Running segmentation")
        seg_result: dict[str, Any] = self._segmenter.segment(input_image)

        # Extract VTK objects per anatomy group
        self.log_section("Extracting VTK objects")
        surfaces: dict[str, pv.PolyData] = {}
        meshes: dict[str, pv.UnstructuredGrid] = {}
        seg_masks: dict[str, Any] = {}

        for group in groups_to_process:
            if group not in seg_result:
                self.log_warning(
                    "Group %s absent from segmentation result — skipping", group
                )
                continue

            mask_image = seg_result[group]
            if int(itk.GetArrayFromImage(mask_image).sum()) == 0:
                self.log_info("Group %s is empty — skipping", group)
                continue

            self.log_info("Processing anatomy group: %s", group)
            seg_masks[group] = mask_image

            label_names, label_ids = self._get_label_info_for_group(group)
            color = self._anatomy_color_map.get(group, (0.7, 0.7, 0.7))

            self.log_info("  Extracting surface for: %s", group)
            base_surface = self._extract_surface(mask_image)
            if base_surface is None:
                continue

            export_surface = base_surface
            if surface_target_reduction > 0.0:
                export_surface = export_surface.decimate_pro(
                    surface_target_reduction, preserve_topology=True
                )
            self._annotate(export_surface, group, label_names, label_ids, color)
            surfaces[group] = export_surface

            self.log_info("  Extracting volume mesh for: %s", group)
            mesh = self._extract_mesh(base_surface, mesh_target_reduction)
            if mesh is not None:
                self._annotate(mesh, group, label_names, label_ids, color)
                meshes[group] = mesh

        self.log_section("IMAGE TO VTK WORKFLOW COMPLETE")
        self.log_info("Surfaces extracted: %d", len(surfaces))
        self.log_info("Meshes extracted:   %d", len(meshes))

        return {
            "surfaces": surfaces,
            "meshes": meshes,
            "labelmap": seg_result["labelmap"],
            "segmentation_masks": seg_masks,
        }

    # ─────────────────────────── I/O helpers ───────────────────────────────

    @staticmethod
    def save_surfaces(
        surfaces: dict[str, pv.PolyData],
        output_dir: str,
        prefix: str = "",
    ) -> dict[str, str]:
        """Save each group surface to its own VTP file.

        Args:
            surfaces: Mapping of anatomy group name → surface (from
                :meth:`run_workflow`).
            output_dir: Directory to write files into (created if absent).
            prefix: Optional filename prefix.  Each file is named
                ``{prefix}_{group}.vtp`` (or ``{group}.vtp`` when *prefix* is empty).

        Returns:
            Mapping of anatomy group name → absolute path of the saved file.
        """
        os.makedirs(output_dir, exist_ok=True)
        saved: dict[str, str] = {}
        for name, surface in surfaces.items():
            stem = f"{prefix}_{name}" if prefix else name
            path = os.path.join(output_dir, f"{stem}.vtp")
            surface.save(path)
            saved[name] = path
        return saved

    @staticmethod
    def save_meshes(
        meshes: dict[str, pv.UnstructuredGrid],
        output_dir: str,
        prefix: str = "",
    ) -> dict[str, str]:
        """Save each group tetrahedral volume mesh to its own VTU file.

        Args:
            meshes: Mapping of anatomy group name → mesh (from :meth:`run_workflow`).
            output_dir: Directory to write files into (created if absent).
            prefix: Optional filename prefix.  Each file is named
                ``{prefix}_{group}.vtu`` (or ``{group}.vtu`` when *prefix* is empty).

        Returns:
            Mapping of anatomy group name → absolute path of the saved file.
        """
        os.makedirs(output_dir, exist_ok=True)
        saved: dict[str, str] = {}
        for name, mesh in meshes.items():
            stem = f"{prefix}_{name}" if prefix else name
            path = os.path.join(output_dir, f"{stem}.vtu")
            mesh.save(path)
            saved[name] = path
        return saved

    @staticmethod
    def save_combined_surface(
        surfaces: dict[str, pv.PolyData],
        output_dir: str,
        prefix: str = "",
    ) -> str:
        """Merge all group surfaces into a single VTP file.

        The merged mesh retains per-cell ``Color`` (RGBA uint8) from each group's
        annotation, enabling colour-by-anatomy rendering in Paraview, PyVista, etc.
        Per-object ``field_data`` is not preserved in the merged file.

        Args:
            surfaces: Mapping of anatomy group name → surface.
            output_dir: Directory to write the file into (created if absent).
            prefix: Optional filename prefix.  Output is ``{prefix}_surfaces.vtp``
                (or ``surfaces.vtp`` when *prefix* is empty).

        Returns:
            Absolute path to the saved VTP file.

        Raises:
            ValueError: If *surfaces* is empty.
        """
        if not surfaces:
            raise ValueError("No surfaces to save.")
        os.makedirs(output_dir, exist_ok=True)
        stem = f"{prefix}_surfaces" if prefix else "surfaces"
        output_file = os.path.join(output_dir, f"{stem}.vtp")
        merged = cast(
            pv.PolyData, pv.merge(list(surfaces.values()), merge_points=False)
        )
        merged.save(output_file)
        return output_file

    @staticmethod
    def save_combined_mesh(
        meshes: dict[str, pv.UnstructuredGrid],
        output_dir: str,
        prefix: str = "",
    ) -> str:
        """Merge all group meshes into a single VTU file.

        The merged mesh retains per-cell ``Color`` (RGBA uint8) from each group's
        annotation.  Per-object ``field_data`` is not preserved in the merged file.

        Args:
            meshes: Mapping of anatomy group name → tetrahedral volume mesh.
            output_dir: Directory to write the file into (created if absent).
            prefix: Optional filename prefix.  Output is ``{prefix}_meshes.vtu``
                (or ``meshes.vtu`` when *prefix* is empty).

        Returns:
            Absolute path to the saved VTU file.

        Raises:
            ValueError: If *meshes* is empty.
        """
        if not meshes:
            raise ValueError("No meshes to save.")
        os.makedirs(output_dir, exist_ok=True)
        stem = f"{prefix}_meshes" if prefix else "meshes"
        output_file = os.path.join(output_dir, f"{stem}.vtu")
        merged = cast(
            pv.UnstructuredGrid, pv.merge(list(meshes.values()), merge_points=False)
        )
        merged.save(output_file)
        return output_file
